spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/schema-based-tenants?currentSchema=saas
    username: postgres
    password: postgres

  main:
    banner-mode: off

server:
  port: 9000
  servlet:
    context-path: /api

